Models/Entities/Attendance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagement.Models.Entities
{
    public class Attendance
    {
        public Guid Id { get; set; }
        public Guid? ClassId { get; set; }
        public Guid? StudentId { get; set; }
        public DateTime? Date { get; set; }
        public bool? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Comment { get; set; }
        public byte[] Attachment { get; set; }
        public int? Number { get; set; }
        public bool? In { get; set; }
        public bool? Out { get; set; }
        public string Name { get; set; }
        public Guid? TeacherId { get; set; }
        public string StudentName { get; set; }
        public String TeacherName { get; set; }
        public string ClassName { get; set; }
        public List<Models.db.AttendanceLog> list{ get; set; }
    }
}

Models/Entities/Class_.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagement.Models.Entities
{
    public class Class_
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int? Grad { get; set; }
        public Guid? TeacherId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Comment { get; set; }
        public byte[] Attachment { get; set; }
        public bool? Status { get; set; }
        public string Shift { get; set; }
        public int? Year { get; set; }
        public string Number { get; set; }
        public string Room { get; set; }
        public List<Models.Entities.Subjetc> SchedualList { get; set; }
        public string TeacherName { get; set; }
        public int NumberOfSubject { get; set; }
    }
}

Models/Entities/TimeTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolManagement.Models.Entities
{
    public class TimeTable
    {
        public Guid Id { get; set; }
        public Guid? ClassId { get; set; }
        public Guid? SubjectId { get; set; }
        public string HourOfDay { get; set; }
        public string DayOfWeek { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? Status { get; set; }
        public int? Year { get; set; }
        public int Number { get; set; }
        public string Teacher { get; set; }
        public string Subject { get; set; }
        public string ClassName { get; set; }
    }
}

Models/db/Attendance.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManagement.Models.db
{
    public partial class Attendance
    {
        public Guid AttendanceId { get; set; }
        public Guid? StudentId { get; set; }
        public DateTime? Date { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Comment { get; set; }
        public byte[] Attachment { get; set; }
        public bool? Status1 { get; set; }
        public int? Number { get; set; }
    }
}

Models/db/Subject.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManagement.Models.db
{
    public partial class Subject
    {
        public Guid Id { get; set; }
        public string SubjectName { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Comment { get; set; }
        public byte[] Attachment { get; set; }
        public bool? Status { get; set; }
        public int? Number { get; set; }
        public int? Grade { get; set; }
        public Guid? TeacherId { get; set; }
        public int? Year { get; set; }
    }
}

Models/db/TimeTable.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManagement.Models.db
{
    public partial class TimeTable
    {
        public Guid Id { get; set; }
        public Guid? ClassId { get; set; }
        public Guid? SubjectId { get; set; }
        public string HourOfDay { get; set; }
        public string DayOfWeek { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public bool? Status { get; set; }
        public int? Year { get; set; }
        public int Number { get; set; }
    }
}

Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolManagement.Models.db;

namespace SchoolManagement.Controllers
{
    public class ClassesController : BaseController
    {
        //private readonly School_dbContext db;

        //public ClassesController(School_dbContext context)
        //{
        //    db = context;
        //}
        public async Task<IActionResult> Attendance()
        {
            return View();
        }
        [HttpPost]
            public async Task<IActionResult> getClassAttendance( Guid? classId, string date,string txtClass)
        {
            try
            {
                // Split authors separated by a comma followed by space
                string[] From_To_Dates = date.Split(new Char[] { '-',/* '\n', '\t', ' ', ',', '.'*/ });
                var StartDate = DateTime.Parse(From_To_Dates[0].ToString());
                var EndDate = DateTime.Parse(From_To_Dates[1].ToString());
                // Calculate the time difference
                TimeSpan difference = StartDate - EndDate;

                ViewBag.startDate = StartDate;ViewBag.endDate = EndDate;
                // Extract the number of days, hours, minutes, etc. from the TimeSpan
                //int daysDifference = difference.Days;
                var daysList = new List<Models.DaysNameAndNumbers> ();
                int number = 1;
       
                // Iterate over the range of dates
                for (DateTime days = StartDate; days <= EndDate; days = days.AddDays(1))
                {
                 
                    daysList.Add(new Models.DaysNameAndNumbers { Name = days.ToString("dddd"),Number=number,day=days.Day});
                    number++;
                }
                ViewBag.daysList = daysList;
                var list = await (from student in db.Students
                                  
                                  where student.ClassId == classId

                                  select new Models.Entities.Attendance
                                  {

                                      StudentId=student.StudentId,
                                      Status = student.Status,
                                      ClassId = student.ClassId,
                                      StudentName = student.FirstName + " " + student.LastName + " " + student.RoleNumber,
                                    list=db.AttendanceLogs.Where(x=>x.Date >= StartDate && x.Date <= EndDate&&x.StudentId==student.StudentId).ToList()




                                  }).AsNoTracking().ToListAsync();

                ViewBag.SystemInfo = db.TableCompanies.FirstOrDefault();
                ViewBag.className = txtClass;
                return PartialView("_Attendance", list);

            }
            catch (Exception ex)
            {

                showMessageString = new
                {
                    status = "false",
                    message = ex.InnerException.Message

                };
                return Json(showMessageString);
            }
            
        }
        public async Task<IActionResult> loadClassSubjects(int? grad, Guid? Id)
        {
            var list =  (from timeTable in db.TimeTables
                              join subject in db.Schedules on timeTable.SubjectId equals subject.Id
                              where timeTable.Status == true && timeTable.ClassId == Id

                              select new Models.Entities.Schedual
                              {


                                  Status = timeTable.Status,

                                  CreatedBy = timeTable.CreatedBy,
                                  ModifiedBy = timeTable.ModifiedBy,
                                  ModifiedDate = timeTable.ModifiedDate,
                                  SubjecName = subject.Subject,
                                  // ClassName=class_.Name,
                                  ClassId = timeTable.ClassId,

                                  Subject = timeTable.SubjectId.ToString(),


                                  CreatedDate = timeTable.CreatedDate,
                                  Id = timeTable.Id,

                                  Number = timeTable.Number,
                                  Year = timeTable.Year,



                              })
                           .AsEnumerable() // Materialize the projection
                  .GroupBy(x => x.SubjecName)
                  .Select(g => g.First()).ToList();
                  
            return PartialView("_Subject",list);
        }
        // GET: Classes
        [HttpPost]
        public async Task<IActionResult> getClassByName(string term)
        {

            var list = await (from class_ in db.Classes


                              where class_.Name.StartsWith(term)

                              select new Models.Entities.Class_
                              {

                                  Id = class_.Id,

                                  Name=class_.Name +" / "+class_.Shift+" / "+class_.Year



                              })/*.OrderByDescending(x => x.CreatedDate)*/.ToListAsync();
            return Json(list);
        }
        [HttpPost]
        public async Task<IActionResult> getClassGrad(int term)
        {

            var list = await (from class_ in db.Classes


                              where class_.Grad==term

                              select new Models.Entities.Class_
                              {

                                  Id = class_.Id,

                                  Name = class_.Name + " / " + class_.Shift + " / " + class_.Year



                              })/*.OrderByDescending(x => x.CreatedDate)*/.ToListAsync();
            return Json(list);
        }
        
        public ActionResult Index(Guid? Id)
        {
         
            IList<Models.Entities.Class_> list = new List<Models.Entities.Class_>();
            //if (Id == null)
            //{
            //    return View(list);
            //}
           
            list = (from class_ in db.Classes
                   join teacher in db.Teachers on class_.TeacherId equals teacher.TeacherId
                   
                    //where id.ClassId == Id

                    select new Models.Entities.Class_
                    {
                      Id=class_.Id,
                        TeacherId = class_.TeacherId,
                        Room = class_.Room,
                        Name = class_.Name,
                        Comment = class_.Comment,
                        CreatedBy = class_.CreatedBy,
                        CreatedDate = class_.CreatedDate,
                        Grad = class_.Grad,
                        ModifiedBy = class_.ModifiedBy,
                        ModifiedDate = class_.ModifiedDate,
                        Number = class_.Number,
                        Attachment = class_.Attachment,
                        Shift = class_.Shift,
                        Status = class_.Status,
                        Year = class_.Year,
                        TeacherName=teacher.FirstName+" "+teacher.LastName +" "+teacher.RoleNumber,
                        SchedualList = (from Schedule in db.Schedules
                                               //join Subject in db.Subjects on Schedule.SubjectId equals Subject.Id
                                               //where Schedule.ClassId==class_.Id
                                               select new Models.Entities.Subjetc
                                               {
                                                   SubjectName = Schedule.Subject,
                                                 
                                               }).ToList()
                       
                    }).ToList();
            return View (list);
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> TimeTable(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var singleClass = (from class_ in db.Classes
                               join teacher in db.Teachers on class_.TeacherId equals teacher.TeacherId

                               where class_.Id == id

                               select new Models.Entities.Class_
                               {
                                   Id = class_.Id,
                                   TeacherId = class_.TeacherId,
                                   Room = class_.Room,
                                   Name = class_.Name,
                                   Comment = class_.Comment,
                                   CreatedBy = class_.CreatedBy,
                                   CreatedDate = class_.CreatedDate,
                                   Grad = class_.Grad,
                                   ModifiedBy = class_.ModifiedBy,
                                   ModifiedDate = class_.ModifiedDate,
                                   Number = class_.Number,
                                   Attachment = class_.Attachment,
                                   Shift = class_.Shift,
                                   Status = class_.Status,
                                   Year = class_.Year,
                                   TeacherName = teacher.FirstName + " " + teacher.LastName + " " + teacher.RoleNumber,
                               }).FirstOrDefault();
            if (singleClass == null)
            {
                return NotFound();
            }
            ViewBag.Class = singleClass;

            var timeTable =await (from class_ in db.TimeTables
                             join shc in db.Schedules on class_.SubjectId equals shc.Id

Views/Classes/Attendance.cshtml
<link rel="stylesheet" href="~/template/assets/plugins/datatables/datatables.min.css">


<div class="content container-fluid">


    <div class="row">
        <div class="col-sm-12">

            <div class="card card-table">
                <div class="card-body">

                    <!-- Page Header -->
                    <div class="page-header">
                        <div class="row align-items-center">
               
                                <form asp-action="getClassAttendance" asp-controller="Classes" method="Post" data-ajax="true"
                                      data-ajax-success="attendanceOnSuccess" data-ajax-begin="OnBegin" data-ajax-complete="OnComplete" data-ajax-failure="OnFailure">
                                    <!-- Form fields go here -->

                      
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="form-group">

                                                <input type="text" id="txtClass" name="txtClass" class="form-control" placeholder="Search class by name ...">
                                                <input type="hidden" id="ClassId" name="classId" />

                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group local-forms">
                                                <label>Event Start Date <span class="login-danger">*</span></label>


                                                <div class="input-group">
                                                    <span class="input-group-text" id="date3-1">Date</span>
                                                    <input type="text" class="form-control" id="inputDate3-1" placeholder="Start - End" aria-label="Dates" aria-describedby="basic-addon1">
                                                </div>
                                                <input type="hidden" name="date" id="date" class="form-control" required />

                                            </div>
                                        </div>

                                        <div class="col-lg-2">
                                            <div class="search-student-btn">
                                                <button type="btn" class="btn btn-primary">Load</button>
                                            </div>
                                        </div>
                                        @*<div class="col-lg-2">
                                            <div class="search-student-btn">
                                                <button onclick="printDiv()" class="btn btn-success"><i class="fa fa-print"></i> Print</button>
                                            </div>
                                        </div>*@
                                    </div>
                                 
                                </form>
                     

                        </div>
                    </div>
                    <!-- /Page Header -->


                    <div id="attendanceList"></div>
                </div>
            </div>
        </div>
    </div>
</div>





<script src="~/template/assets/plugins/datatables/datatables.min.js" type="63ab970d43efa16255dcd8af-text/javascript"></script>
<link href="~/jquery-ui-1.14.1/jquery-ui.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<script src="~/jquery-ui-1.14.1/jquery-ui.min.js"></script>


<link href="~/Persion-datepicker/dist/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />
<script src="~/Persion-datepicker/dist/upper.main.js"></script>
<script src="~/Persion-datepicker/dist/bootstrap.min.js.js"></script>
<script src="~/Persion-datepicker/dist/jquery.md.bootstrap.datetimepicker.js"></script>

<script type="text/javascript">
    $('#date3-1').MdPersianDateTimePicker({
        targetTextSelector: '#inputDate3-1',
        targetDateSelector: '#date',
        monthsToShow: [0, 0],
        selectedDate: new Date(),
        selectedRangeDate: [new Date(), new Date()],
        rangeSelector: true,


    });
</script>

<script>

    $('#txtClass').autocomplete({

        minlength: 3,
        source: function (request, response) {


            var SearchText = $('#txtClass').val();
            //alert(SearchText);
            $('#txtClass').removeClass('notfound');
            $('#txtClass').addClass('loading');

            $.ajax({

                type: "POST",
                async: true,
                url: "/Classes/getClassByName",
                //data: "{term:'" + SearchText + "'}",
                data: { "term": SearchText },
                //contentType: "application/json;characterset=utf-8",

                success: function (data) {
                    if (data.length == 0) {

                        $('#txtClass').removeClass('loading');
                        $('#txtClass').addClass('notfound');


                    }
                    else {
                        $('#txtClass').removeClass('loading');


                    }

                    response($.map(data, function (item) {
                        return { label: item.Name, value: item.Id };
                    }))

                },

                error: function (result) {
                    debugger

                    console.log(result);
                }
            });



        },

        select: function (event, ui) {
    
            $('#txtClass').val(ui.item.label);
              $('#className').val(ui.item.label);

            $('#ClassId').val(ui.item.value);
            $('#txtClass').removeClass('notfound');
            $('#txtClass').addClass('checked');


            return false;

        },



    });
            function printDiv() {




        var divToPrint = document.getElementById('PrintAttendance');

        var newWin = window.open('', 'Print-Window');

        newWin.document.open();

        newWin.document.write(`<html>
           <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">


                <title>


                  ID Card
                </title>
  <style>
                @@media print {
                    table {
                        table-layout: fixed; /* Ensure table keeps its layout for printing */
                        width: 100%; /* Set table width to 100% for printing */
                    }
                    td {
                        width: 1%; /* Force each table cell to take up minimal width */
                        white-space: nowrap; /* Prevent text wrapping in cells */
                    }
                }
            </style>

<head>





            </head>
<body onload="window.print()">` + divToPrint.innerHTML + ' </body></html>');

        newWin.document.close();

        setTimeout(function () { newWin.close(); }, 10);
        $("#Cancel").trigger("click");





    }

</script>
@section Scripts {



    <script>

        function OnBegin() {
            $('.page-loader').show();

        }
        function attendanceOnSuccess(data) {

            if (data.status == "false") {
                swal("False!", data.message, "error");
            }
            else {
                $('#attendanceList').html(data);
            }

        }
        function OnComplete() {
            $('.page-loader').hide();

        }
    </script>
}

Views/Classes/Delete.cshtml
@model SchoolManagement.Models.db.Class

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeacherId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeacherId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attachment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attachment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shift)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shift)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Classes/_index.cshtml
@model IEnumerable<SchoolManagement.Models.Entities.Class_>
<!-- Datatables CSS -->

<style>
    body {
    line-height: 1.6;
    margin: 2em;
}

th {
    background-color: #001f3f;
    color: #fff;
    padding: 0.5em 1em;
}

td {
    border-top: 1px solid #eee;
    padding: 0.5em 1em;
}

input {
    cursor: pointer;
}

/* Column types */
th.missed-col {
    background-color: #f00;
}

td.missed-col {
    background-color: #ffecec;
    color: #f00;
    text-align: center;
}

.name-col {
    text-align: left;
}
</style>
<div class="table-responsive">
    <table class="table border-0 star-student table-hover table-center mb-0 datatable table-striped">
        <thead class="student-thread">
            <tr style="text-align:center">
              <th>#</th>
                <th>Name</th>
                <th>Teacher</th>
                <th>Shift</th>
                <th>Rome</th>

                <th>Year</th>
                <th>Subject#</th>


                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() >= 1)
            {
                int number = 0;
                foreach (var item in Model)
                {


                    <tr style="text-align:center">
                        <td>
                            @number
                        </td>
                        <td><a asp-action="Details" asp-route-id="@item.Id">@item.Name</a> </td>
                        <td>@item.TeacherName</td>
                        <td>@item.Shift </td>
                        <td>@item.Room </td>
                        <td>@item.Year </td>
                        <td>@item.NumberOfSubject </td>
                        <td>
                            <div class="input-group">
                                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">List</button>
                                <div class="dropdown-menu">
                                    
                                    <a onclick='loadAttendance("@item.Id")' href="#" class="dropdown-item">Load Attendance</a>
                                    <a onclick='LoadIdCard("@item.Id")' href="#" class="dropdown-item">Get Students Id</a>
                                    <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id">Edit  </a>

                                    <a class="dropdown-item" asp-action="Create" asp-controller="AttendanceLogs" asp-route-ClassId="@item.Id">  Attendance </a>
                                    <a class="dropdown-item" asp-action="TimeTable" asp-controller="Classes" asp-route-Id="@item.Id"> Time Table   </a>
                                    <a class="dropdown-item" asp-action="TimeTableEdit" asp-controller="Classes" asp-route-Id="@item.Id">Time Table Edit </a>
                                    <a class="dropdown-item" href="#" onclick='LoadSubjects("@item.Id")'>Subjects </a>
                                    <div role="separator" class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Info</a>
                                </div>
                            </div>
                        </td>


                    </tr>
                    number++;
                }
            }
            else
            {
                <tr><td colspan="10"> <h5 style="text-align:center;color:orangered">0 recods founded!</h5></td></tr>

            }



        </tbody>
    </table>
</div>